version: '2'
services:
  tws:
    build: .
    ports:
      - "7497:7497"
      - "7496:7496"
      - "5903:5900"
    environment:
      - TZ=America/New_York
      - VNC_PASSWORD=${VNC_PASSWORD}
      - TWS_USER=${TWS_USER}
      - TWS_PASS=${TWS_PASS}
      #- TWS_PATH=/root/Jts
      #- TWS_CONFIG_PATH=/root/Jts
      #- JAVA_PATH=/opt/i4j_jres/1.8.0_152-tzdata2019c/
