version: '2'
services:
  tws:
    build: .
    ports:
      - "7497:7497"
      - "7496:7496"
      - "5903:5900"
    environment:
      - TZ=America/New_York
      - VNC_PASSWORD=${VNC_PASSWORD}
      - TWS_USER=${TWS_USER}
      - TWS_PASS=${TWS_PASS}
